on:
  pull_request:
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: hashicorp/setup-terraform@v2
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Retrieve Environment Secrets
        run: gobble secrets pr-${{ github.event.number }}-${{ secrets.WRAPPERJS_SECRET_NAME }}
      - name: Remove Back End
        run: gobble sls remove
      - name: Terraform Init
        run: gobble tf init
      - name: Terraform Destroy
        run: gobble tf destroy
      - name: Remove PR Environment
        run: gobble finished pr-${{ github.event.number }}-${{ secrets.WRAPPERJS_SECRET_NAME }}
      - name: Destroy environment if job failed or was cancelled
        if: ${{ failure() || cancelled() }}
        run: gobble sls remove && gobble tf destroy && gobble finished ${{ secrets.WRAPPERJS_SECRET_NAME }}  