service: ${file(./../../serverless.env.json):service_name}-${file(./../../serverless.env.json):stage}-${self:custom.service}
useDotenv: true
projectDir: ../../

provider:
  environment: ${file(./../../serverless.env.json)}
  name: aws
  region: ${file(./../../serverless.env.json):region}
  runtime: nodejs12.x
  stage: ${file(./../../serverless.env.json):stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
  # apiGateway: # Optional API Gateway global config
    # websocketApiId: ${file(./../../../serverless.env.json):ws_api_gateway_rest_api_id} # REST API resource ID. Default is generated by the framework
    # restApiRootResourceId: ${file(./../../../serverless.env.json):ws_api_gateway_root_resource_id} # Root resource ID, represent as / path
  deploymentBucket: 
    name: ${file(./../../serverless.env.json):state_s3_bucket}-${self:custom.service}
    serverSideEncryption: AES256
  websocketsApiRouteSelectionExpression: $request.body.action


functions:
  - ${file(default/lambda.yml)}
  - ${file(connect/lambda.yml)}
  - ${file(positions/lambda.yml)}

plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-domain-manager
  
custom:
  service: sockets
  serverless-offline:
    host: '0.0.0.0'
  customDomain:
    websocket:
      domainName: ws.${file(./../../serverless.env.json):domain_name}
      stage: ${file(./../../serverless.env.json):stage}
      basePath: ''
      certificateName: ' ws.${file(./../../serverless.env.json):domain_name}'
      createRoute53Record: true
      endpointType: 'regional'
      enabled: true
      securityPolicy: tls_1_2