on:
  push:
    branches: 
      - feature/*

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        uses: actions/checkout
        uses: actions/setup-node
        uses: hashicorp/setup-terraform
        uses: serverless/github-action
        run: echo "hello world :D"
        run: echo "terraform --version"
        run: echo "serverless --version"
        run: echo "node --version"