on:
  push:
    branches: 
      - feature/*

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello world :D"
      - run: echo "terraform --version"
      - run: echo "serverless --version"
      - run: echo "node --version"