on:
  pull_request:
    branches: 
      - $default-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: hashicorp/setup-terraform@v2
      - name: check PR
        run: echo ${{ github.event.number }}