on:
  push:
    branches: 
      - feature/*

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: echo "hello world :D"
      - run: node --version