on:
  push:
    branches: 
      - feature/*

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 3.27.0
      - name: Install Serverless Framework
        run: npm install -g serverless
      - run: echo "hello world :D"
      - run: node --version
      - run: terraform --version
      - run: serverless --version